const data = [
  {
    questionText: 'İtalya’nın en uzun nehri ___________ nehridir.',
    level: 3,
    optionA: 'Mur',
    optionB: 'Ren',
    optionC: 'Volga',
    optionD: 'Po',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: '___________ bir canlının veya bir hücrenin kalıtım öğelerinde birdenbire ve düzensiz olarak meydana gelen değişimdir.',
    level: 2,
    optionA: 'Evrim',
    optionB: 'Mutasyon',
    optionC: 'Adaptasyon',
    optionD: 'Modifikasyon ',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'B',
  },
  {
    questionText: 'Farklı çeşitlerin, soy, ırk ve halkların birleşmesinden ortaya çıkan türe ___________ adı verilir.',
    level: 2,
    optionA: 'Kırma',
    optionB: 'Hibrit',
    optionC: 'Melez',
    optionD: 'Metis',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'C',
  },
  {
    questionText: 'Gücünü arttırmak için ıspanak yiyen çizgi roman karakteri ___________.',
    level: 1,
    optionA: 'Safinaz’dır',
    optionB: 'Kaba Sakal’dır',
    optionC: 'Wimpy’dir',
    optionD: 'Temel Reis’tir',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: 'Dünyanın en büyük resim müzelerinden biri olan National Gallery ___________.',
    level: 2,
    optionA: 'Berlin’dedir',
    optionB: 'Londra’dadır',
    optionC: 'Prag’dadır',
    optionD: 'Venedik’tedir',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'B',
  },
  {
    questionText: 'Radyo dalgalarının yansımasıyla uzak cisimlerin saptanması ve konumlarının belirlenmesini sağlayan aygıt ___________.',
    level: 2,
    optionA: 'Uydu’dur',
    optionB: 'Radar’dır',
    optionC: 'Çanak’tır',
    optionD: 'Sensör’dür ',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'B',
  },
  {
    questionText: 'Kendi rengini çevresine göre değiştiren kertenkele türü ___________.',
    level: 1,
    optionA: 'Sakallı ejder',
    optionB: 'İguana',
    optionC: 'Bukalemun',
    optionD: 'Uçan Gecko',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'C',
  },
  {
    questionText: '___________ kemiklerin iç boşluklarını dolduran, yumuşak, pelte kıvamındaki maddeye denir.',
    level: 1,
    optionA: 'Kıkırdak',
    optionB: 'Zar',
    optionC: 'İlik',
    optionD: 'Damar',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'C',
  },
  {
    questionText: 'Bütün kış boyunca, bazı hayvanların girdiği uzun süreli uyku___________.',
    level: 1,
    optionA: 'Siesta Uykusudur',
    optionB: 'TazelenmeUykusudur',
    optionC: 'BaharUykusu',
    optionD: 'KışUykusu',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: 'Güney Amerika’nın yüzölçümü en geniş ülkesi___________.',
    level: 2,
    optionA: 'Arjantin’dir',
    optionB: 'Peru’dur',
    optionC: 'Brezilya’dır',
    optionD: 'Kolombiya’dır',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'C',
  },
  {
    questionText: 'Birleşmiş Milletler Örgütü’ne bağlı bir kurum olan UNESCO’nun merkezi___________.',
    level: 3,
    optionA: 'Berlinde’dir',
    optionB: 'Pariste’dir',
    optionC: 'Venedikte’dir',
    optionD: 'Pragta’dır',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'B',
  },
  {
    questionText: 'Balıkesir ili___________bölgemizdedir.',
    level: 2,
    optionA: 'Ege',
    optionB: 'Karadeniz',
    optionC: 'Akdeniz',
    optionD: 'Marmara',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: 'İnsülin üreten organ___________.',
    level: 2,
    optionA: 'Karaciğer',
    optionB: 'Bağırsak',
    optionC: 'Pankreas',
    optionD: 'Mide',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'C',
  },
  {
    questionText: '___________milimetrenin binde biridir.',
    level: 3,
    optionA: 'Mikron',
    optionB: 'Angstrom',
    optionC: 'Fermi',
    optionD: 'Nano',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'A',
  },
  {
    questionText: 'Tiyatroda oyuncuların uzun soluklu konuşmasına___________denir.',
    level: 2,
    optionA: 'Monolog',
    optionB: 'Dialog',
    optionC: 'Tirat',
    optionD: 'Hitabet',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'C',
  },
  {
    questionText: 'Deri hastalıkları üzerine uzmanlaşmış medikal doktora___________denir.',
    level: 1,
    optionA: 'Radyolog',
    optionB: 'Hematolog',
    optionC: 'Nörolog',
    optionD: 'Dermatolog',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: '___________spor karşılaşmalarında bir takımın rakip takımın sahasında karşılaşmaya gitmesine verilen addır.',
    level: 1,
    optionA: 'Bonservis',
    optionB: 'Deplasman',
    optionC: 'Jübile',
    optionD: 'Averaj',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'B',
  },
  {
    questionText: 'Okyanusya’da Cook boğazıyla birbirine bağlanan iki adadan oluşan ülke___________.',
    level: 3,
    optionA: 'Japonya’dır',
    optionB: 'Yeni Zelanda’dır',
    optionC: 'Tayvan’dır',
    optionD: 'İtalya’dır',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'B',
  },
  {
    questionText: 'Sıtma mikrobunu taşıyan sivrisineğe___________denir.',
    level: 3,
    optionA: 'Anofel',
    optionB: 'Mansonia',
    optionC: 'Sarı Humma',
    optionD: 'Aedes',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'A',
  },
  {
    questionText: '___________Roma’nın içinden geçen nehirdir.',
    level: 3,
    optionA: 'Tiber',
    optionB: 'Po',
    optionC: 'Adige',
    optionD: 'Adda',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'A',
  },
  {
    questionText: 'Tıp öğreniminde kullanılmak üzere, özel korunan insan ya da hayvan ölülerine___________denir.',
    level: 1,
    optionA: 'Mangala',
    optionB: 'Ceset',
    optionC: 'Denek',
    optionD: 'Kadavra',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: 'İtalya’nın kanalları ile meşhur olan şehri___________.',
    level: 1,
    optionA: 'Prag’dır',
    optionB: 'Berlin’dir',
    optionC: 'Paris’tir',
    optionD: 'Venedik’tir',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: '___________ortaçağ’daki toprak ağasına denir.',
    level: 2,
    optionA: 'Beylerbeyi',
    optionB: 'Derebeyi',
    optionC: 'Atabey',
    optionD: 'Boybeyi',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'B',
  },
  {
    questionText: '___________Osmanlıca’da ’seyyare’ demektir.',
    level: 3,
    optionA: 'Yıldız',
    optionB: 'Samanyolu',
    optionC: 'Galaksi',
    optionD: 'Gezegen',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: 'En hızlı koşan hayvan___________.',
    level: 1,
    optionA: 'Çita',
    optionB: 'Tavşan',
    optionC: 'Tazı',
    optionD: 'Devekuşu',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'A',
  },
  {
    questionText: '___________2600 metre ile dünyanın en yüksek kıtasıdır.',
    level: 3,
    optionA: 'Asya',
    optionB: 'Antarktika',
    optionC: 'Amerika',
    optionD: 'Avustralya',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'B',
  },
  {
    questionText: 'Motorsuz uçağa___________denir.',
    level: 2,
    optionA: 'Paramotor',
    optionB: 'Planör',
    optionC: 'Cayrokopter',
    optionD: 'Yelkenkanat',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'B',
  },
  {
    questionText: '___________Afrika’nın Mısır dışındaki kuzey ülkelerine verilen ortak isimdir.',
    level: 3,
    optionA: 'Patagonya',
    optionB: 'Hispanik',
    optionC: 'Malay',
    optionD: 'Mağrip',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: 'Avustralya dışında, Dünya’daki en büyükada___________adasıdır.',
    level: 3,
    optionA: 'Grönland',
    optionB: 'Yeni Gine',
    optionC: 'Borneo',
    optionD: 'Madagaskar',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'A',
  },
  {
    questionText: 'Atletizm karşılaşmalarında atılan mızrak benzeri obje___________.',
    level: 2,
    optionA: 'Disk',
    optionB: 'Cirit',
    optionC: 'Kargı',
    optionD: 'Ok',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'B',
  },
  {
    questionText: 'Deniz seviyesinden ortalama yüksekliği en az olan kıta___________.',
    level: 3,
    optionA: 'Antarktika',
    optionB: 'Amerika',
    optionC: 'Asya',
    optionD: 'Avustralya',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: 'Çek Cumhuriyeti’nin başkenti___________.',
    level: 1,
    optionA: 'Paris’tir',
    optionB: 'Prag’dır',
    optionC: 'Venedik’tir',
    optionD: 'Berlin’dir',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'B',
  },
  {
    questionText: 'Osmanlı Devleti’nin farklı tarihlerde iki kez kuşatmasına rağmen alamadığı Avrupa şehri___________.',
    level: 1,
    optionA: 'Venedik’tir',
    optionB: 'Budapeşte’dir',
    optionC: 'Bratislava’dır',
    optionD: 'Viyana’dır',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: 'Kasparov___________alanında dünyaca ünlü bir isimdir.',
    level: 2,
    optionA: 'Satranç',
    optionB: 'Futbol',
    optionC: 'Tıp',
    optionD: 'Sudoku',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'A',
  },
  {
    questionText: 'Güneş sistemindeki en büyük gezegen___________.',
    level: 2,
    optionA: 'Satürn',
    optionB: 'Uranüs',
    optionC: 'Jüpiter',
    optionD: 'Mars',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'C',
  },
  {
    questionText: 'Kır hayatını, köylerdeki yaşayış şeklini konu alan şiire___________adı verilir.',
    level: 2,
    optionA: 'Lirik',
    optionB: 'Didaktik',
    optionC: 'Pastoral',
    optionD: 'Satirik',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'C',
  },
  {
    questionText: 'Çok sayıda gayrimüslim vatandaşın iflasına yol açan 1942 tarihli vergi kanununun adı___________.',
    level: 1,
    optionA: 'Gelir Vergisi',
    optionB: 'Satış Vergisi',
    optionC: 'Varlık Vergisi',
    optionD: 'Alış Vergisi',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'C',
  },
  {
    questionText: 'İlk alfabeyi___________oluşturmuştur.',
    level: 3,
    optionA: 'Fenikeliler',
    optionB: 'Sümerler',
    optionC: 'Lidya',
    optionD: 'Roma',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'A',
  },
  {
    questionText: '___________Yunan mitolojisinde yer alan efsanevi tek gözlü canavardır.',
    level: 3,
    optionA: 'Medusa',
    optionB: 'Hidra',
    optionC: 'Siren',
    optionD: 'Tepegöz',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: 'Bir binayı ya da mülkü kasıtlı bir şekilde ateşe vermeye___________denir.',
    level: 1,
    optionA: 'Yağma',
    optionB: 'Kundaklama',
    optionC: 'Şantaj',
    optionD: 'Cebir',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'B',
  },
  {
    questionText: '___________el ele tutuşarak, omuz omuza ya da kol kola oynanan halk oyununun adıdır.',
    level: 1,
    optionA: 'Misket',
    optionB: 'Zeybek',
    optionC: 'Hançer barı',
    optionD: 'Halay',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: 'Boğaziçi köprüsü___________yılında kullanıma açılmıştır.',
    level: 3,
    optionA: '1971',
    optionB: '1975',
    optionC: '1973',
    optionD: '1977',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'C',
  },
  {
    questionText: 'Rupi___________para birimidir.',
    level: 2,
    optionA: 'Rusya',
    optionB: 'Brezilya',
    optionC: 'Hindistan',
    optionD: 'Avustralya',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'C',
  },
  {
    questionText: 'Türk Halk Edebiyatında şairlerin asıl adlarının yerine kullandıkları takma ada___________denir.',
    level: 1,
    optionA: 'Tapşırma',
    optionB: 'Müstear',
    optionC: 'Lakap',
    optionD: 'Mahlas',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'D',
  },
  {
    questionText: 'Tavlada (3+3) atılan zara___________adı verilir.',
    level: 3,
    optionA: 'Düsse',
    optionB: 'Şeşiyek',
    optionC: 'Şeşidü',
    optionD: 'Pencüse',
    optionE: 'Hatırlamıyorum',
    correctAnswer: 'A',
  },
];

export default data;
