const data = [
  '/audioFiles/recallListening/1.mp3',
  '/audioFiles/recallListening/2.mp3',
  '/audioFiles/recallListening/3.mp3',
  '/audioFiles/recallListening/4.mp3',
  '/audioFiles/recallListening/5.mp3',
  '/audioFiles/recallListening/6.mp3',
  '/audioFiles/recallListening/7.mp3',
  '/audioFiles/recallListening/8.mp3',
  '/audioFiles/recallListening/9.mp3',
  '/audioFiles/recallListening/10.mp3',
  '/audioFiles/recallListening/11.mp3',
  '/audioFiles/recallListening/12.mp3',
  '/audioFiles/recallListening/13.mp3',
  '/audioFiles/recallListening/14.mp3',
  '/audioFiles/recallListening/15.mp3',
  '/audioFiles/recallListening/16.mp3',
  '/audioFiles/recallListening/17.mp3',
  '/audioFiles/recallListening/18.mp3',
  '/audioFiles/recallListening/19.mp3',
  '/audioFiles/recallListening/20.mp3',
  '/audioFiles/recallListening/21.mp3',
  '/audioFiles/recallListening/22.mp3',
  '/audioFiles/recallListening/23.mp3',
  '/audioFiles/recallListening/24.mp3',
  '/audioFiles/recallListening/25.mp3',
  '/audioFiles/recallListening/26.mp3',
  '/audioFiles/recallListening/27.mp3',
  '/audioFiles/recallListening/28.mp3',
  '/audioFiles/recallListening/29.mp3',
  '/audioFiles/recallListening/30.mp3',
];

export default data;
