const data = [
  'Tepegöz Yunan mitolojisinde yer alan efsanevi tek gözlü canavardır.',
  'İnsülin üreten organ pankreastır.',
  'Güney Amerika’nın yüzölçümü en geniş ülkesi Brezilya’dır.',
  'Deri hastalıkları üzerine uzmanlaşmış medikal doktora dermatolog denir.',
  'İlk alfabeyi Fenikeliler oluşturmuştur.',
  'Deniz seviyesinden ortalama yüksekliği en az olan kıta Avustralya’dır.',
  'Sıtma mikrobunu taşıyan sivrisineğe anofel denir.',
  'Kasparov satranç alanında dünyaca ünlü bir isimdir.',
  'Tıp öğreniminde kullanılmak üzere, özel korunan insan ya da hayvan ölülerine kadavra denir.',
  'Birleşmiş Milletler Örgütü’ne bağlı bir kurum olan UNESCO’nun merkezi Pariste’dir.',
  'Çok sayıda gayrimüslim vatandaşın iflasına yol açan 1942 tarihli vergi kanununun adı varlık vergisidir.',
  'Gücünü arttırmak için ıspanak yiyen çizgi roman karakteri Temel Reis’tir.',
  'Tiber Roma’nın içinden geçen nehirdir.',
  'Çek Cumhuriyeti’nin başkenti Prag’dır.',
  'Motorsuz uçağa planör denir.',
  'İtalya’nın en uzun nehri Po’dur.',
  'Tiyatroda oyuncuların uzun soluklu konuşmasına tirat denir.',
  'Bütün kış boyunca, bazı hayvanların girdiği uzun süreli uyku kış uykusudur.',
  'Güneş sistemindeki en büyük gezegen Jüpiter’dir.',
  'Antarktika 2600 metre ile dünyanın en yüksek kıtasıdır.',
  ' Boğaziçi köprüsü 1973 yılında kullanıma açılmıştır.',
  'Radyo dalgalarının yansımasıyla uzak cisimlerin saptanması ve konumlarının belirlenmesini sağlayan aygıt radardır.',
  'İtalya’nın kanalları ile meşhur olan şehri Venedik’tir.',
  'Bir binayı ya da mülkü kasıtlı bir şekilde ateşe vermeye kundaklama denir.',
  'Kır hayatını, köylerdeki yaşayış şeklini konu alan şiire pastoral adı verilir.',
  'Atletizm karşılaşmalarında atılan mızrak benzeri obje cirittir.',
  'En hızlı koşan hayvan Çita’dır.',
  'Okyanusya’da Cook boğazıyla birbirine bağlanan iki adadan oluşan ülke Yeni Zelanda’dır.',
  'Rupi Hindistanın para birimidir.',
  'Kendi rengini çevresine göre değiştiren kertenkele türü bukalemundur.',
];

export default data;
