const data = [
  'Dünyanın en büyük resim müzelerinden biri olan National Gallery Londra’dadır.',
  'Güneş sistemindeki en büyük gezegen Jüpiter’dir.',
  'Atletizm karşılaşmalarında atılan mızrak benzeri obje cirittir',
  'Mağrip Afrika’nın Mısır dışındaki kuzey ülkelerine verilen ortak isimdir.',
  'Okyanusya’da Cook boğazıyla birbirine bağlanan iki adadan oluşan ülke Yeni Zelanda’dır.',
  'Motorsuz uçağa planör denir.',
  'Güney Amerika’nın yüzölçümü en geniş ülkesi Brezilya’dır.',
  'Çok sayıda gayrimüslim vatandaşın iflasına yol açan 1942 tarihli vergi kanununun adı varlık vergisidir.',
  'Türk Halk Edebiyatında şairlerin asıl adlarının yerine kullandıkları takma ada mahlas denir.',
  'Çek Cumhuriyeti’nin başkenti Prag’dır.',
  'Derebeyi ortaçağ’daki toprak ağasına denir.',
  'Kır hayatını, köylerdeki yaşayış şeklini konu alan şiire pastoral adı verilir.',
  'Balıkesir ili Marmara bölgemizdedir.',
  'Birleşmiş Milletler Örgütü’ne bağlı bir kurum olan UNESCO’nun merkezi Pariste’dir.',
  'En hızlı koşan hayvan Çita’dır.',
  'Gücünü arttırmak için ıspanak yiyen çizgi roman karakteri Temel Reis’tir.',
  'Antarktika 2600 metre ile dünyanın en yüksek kıtasıdır.',
  'Tıp öğreniminde kullanılmak üzere, özel korunan insan ya da hayvan ölülerine kadavra denir.',
  'Radyo dalgalarının yansımasıyla uzak cisimlerin saptanması ve konumlarının belirlenmesini sağlayan aygıt radardır.',
  'İtalya’nın en uzun nehri Po nehridir.',
  'Mutasyon bir canlının veya bir hücrenin kalıtım öğelerinde birdenbire ve düzensiz olarak meydana gelen değişimdir.',
  'Deniz seviyesinden ortalama yüksekliği en az olan kıta Avustralya’dır.',
  'Bir binayı ya da mülkü kasıtlı bir şekilde ateşe vermeye kundaklama denir.',
  'Tiyatroda oyuncuların uzun soluklu konuşmasına tirat denir.',
  'Rupi Hindistanın para birimidir.',
  'Mikron milimetrenin binde biridir.',
  'Osmanlı Devleti’nin farklı tarihlerde iki kez kuşatmasına rağmen alamadığı Avrupa şehri Viyana’dır.',
  'Sıtma mikrobunu taşıyan sivrisineğe anofel denir.',
  'Bütün kış boyunca, bazı hayvanların girdiği uzun süreli uyku kış uykusudur.',
  'Tavlada (3+3) atılan zara düsse adı verilir.',
  'Tiber Roma’nın içinden geçen nehirdir.',
  'Avustralya dışında, Dünya’daki en büyük ada Grönland adasıdır.',
  'İnsülin üreten organ pankreastır.',
  'Deri hastalıkları üzerine uzmanlaşmış medikal doktora dermatolog denir.',
  'Tepegöz Yunan mitolojisinde yer alan efsanevi tek gözlü canavardır.',
  'Kasparov satranç alanında dünyaca ünlü bir isimdir.',
  'Kendi rengini çevresine göre değiştiren kertenkele türü bukalemundur.',
  'Deplasman spor karşılaşmalarında bir takımın rakip takımın sahasında karşılaşmaya gitmesine verilen addır.',
  'İlik kemiklerin iç boşluklarını dolduran, yumuşak, pelte kıvamındaki maddeye denir.',
  'Halay el ele tutuşarak, omuz omuza ya da kol kola oynanan halk oyununun adıdır.',
  'Boğaziçi köprüsü 1973 yılında kullanıma açılmıştır.',
  'Gezegen Osmanlıca’da ’seyyare’ demektir.',
  'Farklı çeşitlerin, soy, ırk ve halkların birleşmesinden ortaya çıkan türe melez adı verilir.',
  'İlk alfabeyi Fenikeliler oluşturmuştur.',
  'İtalya’nın kanalları ile meşhur olan şehri Venedik’tir.',
];

export default data;
